# Generated by Django 5.2.6 on 2025-09-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_selected_preferences',
            field=models.BooleanField(default=False),
        ),
    ]
