# Generated by Django 5.2.6 on 2025-09-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_has_selected_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
